### ISSUE TITLE
Authentication credentials were not provided when applying drf

### ISSUE THREAD

**Issue by stevenxvii** [pgorecki/django-cancango#4]
Hello guys,

I am wondering if anyone have the same issue, everything works fine till I apply the ability for django rest framework,

For generic views, I can get the queryset correctly, without any problem, but for DRF viewset it will return “ Authentication credentials were not provided”

I run both at the same time, the one with generic views will return correct queryset (even for Anonymous), the one with DRF viewset always return “ Authentication credentials were not provided” 

define_access_rules > as in instruction, allow(‘view’, model)
set_aliases_for_drf_actions > as in instruction, alias_action(“list”, “view”) and so on

I also made a new project just for testing, setup everything as in the instruction still got the same issue

I really appreciate for your help
Best regards,

**Comment by stevenxvii** [comment]
For more information, define_access_rules as in the instruction

```
def define_access_rules(user, rules):
    # Anybody can view published articles
    rules.allow('view', Article, published=True)

    if not user.is_authenticated:
        return 

    # Allow logged in user to view his own articles, regardless of the `published` status
    # allow accepts the same kwargs that you would provide to QuerySet.filter method
    rules.allow('view', Article, author=user)
```

**Comment by pgorecki** [comment]
can you share  the DRF viewset you are using?
